### ISSUE TITLE
`cat *current.yaml`

### ISSUE THREAD

**Issue by RedNo7** [kaijk/openweathermap#1]
Hi,

Firstly, this is awesome!! (and has helped me learn about `sed`) 👍 

`createopenweather` has the following section:
```yaml
# Current Conditions
cat *current.yaml      >> openweather.yaml
```

...but there is no `current.yaml`.  Have I missed something?

**Comment by kaijk** [comment]
Oops. How'd that happen?  I'm traveling,  but I will try to at least reply
here with the file contents. Sorry about that.

**Comment by RedNo7** [comment]
No need to apologise - I really appreciate you sharing this in the first place!

**Comment by kaijk** [comment]
I uploaded the missing file. Let me know how it goes. 
Thanks for letting me know

**Comment by RedNo7** [comment]
will do - cheers.

**Comment by RedNo7** [comment]
Perfect - thanks so much! 👍
